server:
  port: 8182

#data base config : mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: YourDBPassCode
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
